import './globals.css'

export const metadata = {
  title: 'Create React App',
  description: 'Generated by create react app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
